services:
  vtn:
    build:
      dockerfile: vtn.Dockerfile
      context: .
    ports:
      - ${VTN_PORT}:3000
    environment:
      RUST_LOG: debug
      DATABASE_URL: postgres://openadr:openadr@db:5432/openadr
    healthcheck:
      test: curl --fail http://127.0.0.1:3000/programs || exit 1
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - db

  db:
    image: ghcr.io/tweedegolf/postgres:16
    environment:
      POSTGRES_USER: $PG_USER 
      POSTGRES_DB: $PG_DB
      POSTGRES_PASSWORD: $PG_PASSWORD
      TZ: $PG_TZ
    ports: 
      - ${PG_PORT}:5432
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
